package oauth2

// ConfigStub is the configuration file published into a project.
//
// It follows the shape queue and cache use: a config.Set of a single section,
// every leaf read through config.MustEnv so a deployment can override it
// without editing Go.
const ConfigStub = `package configs

import (
	"github.com/lemmego/api/config"
)

func init() {
	config.Set("oauth", config.M{
		// Where the endpoints are mounted. The discovery document and the
		// JWKS always live at the root, as RFC 8414 requires, and are not
		// affected by this.
		"route_prefix": config.MustEnv("OAUTH_ROUTE_PREFIX", "/oauth"),

		// The iss claim of every token, and the issuer in the discovery
		// document. Getting this wrong breaks every consumer and is
		// invisible until integration, so it is checked at boot.
		"issuer": config.MustEnv("OAUTH_ISSUER", config.MustEnv("APP_URL", "")),

		// The RSA keypair tokens are signed with. Generated by
		// ` + "`lemmego run oauth:keys`" + ` and kept out of version control:
		// storage/ is already gitignored.
		"keys": config.M{
			"path":   config.MustEnv("OAUTH_KEYS_PATH", "./storage/oauth"),
			"length": config.MustEnv("OAUTH_KEY_LENGTH", 2048),
		},

		"ttl": config.M{
			"access_token":   config.MustEnv("OAUTH_ACCESS_TOKEN_TTL", "1h"),
			"refresh_token":  config.MustEnv("OAUTH_REFRESH_TOKEN_TTL", "336h"),
			"auth_code":      config.MustEnv("OAUTH_AUTH_CODE_TTL", "60s"),
			"device_code":    config.MustEnv("OAUTH_DEVICE_CODE_TTL", "600s"),
			"personal_token": config.MustEnv("OAUTH_PERSONAL_TOKEN_TTL", "8760h"),
		},

		// PKCE is required of every client by default, not only public ones.
		// RFC 9700 recommends it for all of them.
		"require_pkce": config.MustEnv("OAUTH_REQUIRE_PKCE", true),

		// A refresh token is single use. Presenting a rotated one revokes
		// everything descended from the same grant, including the token the
		// honest client holds: one of the two holders is an attacker and the
		// server cannot tell which.
		"refresh_rotation": config.MustEnv("OAUTH_REFRESH_ROTATION", true),

		// How long a rotated refresh token still works, for clients that
		// crash between receiving one and storing it. Any non-zero value
		// measurably weakens reuse detection.
		"reuse_grace_period": config.MustEnv("OAUTH_REUSE_GRACE_PERIOD", "0s"),

		// Whether each request checks the token's revocation row.
		//   always — correct, one indexed read per request
		//   cached — reopens a revocation window as long as the cache TTL
		//   never  — a revoked token works until it expires
		"revocation": config.MustEnv("OAUTH_REVOCATION", "always"),

		// A first-party client is one the application itself owns, so there
		// is nobody to ask for consent.
		"skip_consent_for_first_party": config.MustEnv("OAUTH_SKIP_FIRST_PARTY_CONSENT", true),

		// Where to send someone who reaches the consent screen without being
		// signed in.
		"login_route": config.MustEnv("OAUTH_LOGIN_ROUTE", "/login"),

		// The page at {route_prefix}/clients where a signed-in user
		// registers and revokes their own clients. It lists only their own,
		// so it needs no administrator role.
		"management_routes": config.MustEnv("OAUTH_MANAGEMENT_ROUTES", true),

		// The scopes clients may request, and what to show on the consent
		// screen for each. A scope that is not listed here is rejected
		// rather than silently dropped.
		"scopes": config.M{},

		// Origins allowed to call the token and device endpoints from a
		// browser. Comma separated; empty means none.
		"cors_origins": config.MustEnv("OAUTH_CORS_ORIGINS", ""),

		// How long a revoked or expired row is kept before oauth:purge
		// removes it.
		"prune_after_hours": config.MustEnv("OAUTH_PRUNE_AFTER_HOURS", 168),

		"table_prefix": config.MustEnv("OAUTH_TABLE_PREFIX", "oauth_"),
	})
}
`

// MigrationVersion is the version the published migration registers under.
//
// It is a fixed constant rather than a timestamp taken when the file is
// written, which is how Passport does it too. A generated timestamp would
// differ on every run, so publishing twice would leave two migrations
// creating the same tables — and the migrator appends a duplicate version to
// its ordered list rather than rejecting it, which would run one of them
// twice. A constant makes a second publish a no-op, which is what anyone
// running it expects.
const MigrationVersion = "20260101000000"

// MigrationStub is the migration published into a project.
//
// The schema is spelled out here rather than delegated back to this package.
// That is the whole point of publishing it: the file becomes the project's,
// so a column can be added, a type changed, or a table dropped outright. A
// stub that called SchemaStatements would look like ownership and give none
// of it — changing anything would mean forking the package.
//
// The cost is that this and SchemaStatements can drift.
// TestPublishedMigrationMatchesTheSchema pins them together so the drift is
// caught here rather than shipped, and after a project publishes the file the
// two are meant to diverge.
//
// The form matches the migration a scaffolded project already has for its
// users table, so it reads like something the project wrote.
const MigrationStub = `package migrations

import (
	"database/sql"

	"github.com/lemmego/migration"
)

func init() {
	migration.GetMigrator().AddMigration(&migration.Migration{
		Version: "20260101000000",
		Up:      mig_20260101000000_create_oauth2_tables_up,
		Down:    mig_20260101000000_create_oauth2_tables_down,
	})
}

// The OAuth2 server's tables. This file belongs to your project: change a
// column, add one, or drop a table you do not need. Nothing in the oauth2
// package reads it back, so an edit here is yours to keep.
//
// What the server does expect is that the columns it reads and writes exist
// with compatible types. Removing oauth_device_codes disables the device
// grant; removing a column the server writes will fail at runtime rather
// than at migrate time.
func mig_20260101000000_create_oauth2_tables_up(tx *sql.Tx) error {
	if _, err := tx.Exec(migration.Create("oauth_clients", func(t *migration.Table) {
		t.String("id", 64).Primary()
		t.String("user_id", 64).Nullable()
		t.String("name", 255)
		t.String("secret", 64).Nullable()
		t.Text("redirect_uris")
		t.Text("grant_types")
		t.Text("scopes").Nullable()
		t.Boolean("confidential").Default(true)
		t.Boolean("first_party").Default(false)
		t.Boolean("revoked").Default(false)
		t.DateTime("created_at", 6).Default(migration.CurrentTimestamp)
		t.DateTime("updated_at", 6).Default(migration.CurrentTimestamp)
		t.Index("user_id")
	}).Build()); err != nil {
		return err
	}

	if _, err := tx.Exec(migration.Create("oauth_auth_codes", func(t *migration.Table) {
		t.String("id", 64).Primary()
		t.String("user_id", 64)
		t.String("client_id", 64)
		t.Text("scopes")
		t.Text("redirect_uri")
		t.String("code_challenge", 128).Nullable()
		t.String("code_challenge_method", 10).Nullable()
		t.String("family_id", 64)
		t.DateTime("expires_at", 6)
		t.DateTime("consumed_at", 6).Nullable()
		t.Boolean("revoked").Default(false)
		t.DateTime("created_at", 6).Default(migration.CurrentTimestamp)
		t.Index("client_id")
		t.Index("expires_at")
	}).Build()); err != nil {
		return err
	}

	if _, err := tx.Exec(migration.Create("oauth_access_tokens", func(t *migration.Table) {
		t.String("id", 80).Primary()
		t.String("user_id", 64).Nullable()
		t.String("client_id", 64)
		t.String("name", 255).Nullable()
		t.Text("scopes")
		t.String("family_id", 64)
		t.Boolean("revoked").Default(false)
		t.DateTime("expires_at", 6)
		t.DateTime("created_at", 6).Default(migration.CurrentTimestamp)
		t.DateTime("updated_at", 6).Default(migration.CurrentTimestamp)
		t.Index("user_id")
		t.Index("client_id")
		t.Index("family_id")
		t.Index("expires_at")
	}).Build()); err != nil {
		return err
	}

	if _, err := tx.Exec(migration.Create("oauth_refresh_tokens", func(t *migration.Table) {
		t.String("id", 64).Primary()
		t.String("access_token_id", 80).Nullable()
		t.String("client_id", 64)
		t.String("user_id", 64).Nullable()
		t.Text("scopes")
		t.String("family_id", 64)
		t.String("rotated_to", 64).Nullable()
		t.Boolean("revoked").Default(false)
		t.DateTime("expires_at", 6)
		t.DateTime("created_at", 6).Default(migration.CurrentTimestamp)
		t.Index("access_token_id")
		t.Index("family_id")
		t.Index("expires_at")
	}).Build()); err != nil {
		return err
	}

	if _, err := tx.Exec(migration.Create("oauth_device_codes", func(t *migration.Table) {
		t.String("id", 64).Primary()
		t.String("user_code_hash", 64).Unique()
		t.String("client_id", 64)
		t.String("user_id", 64).Nullable()
		t.Text("scopes")
		t.String("family_id", 64)
		t.Int("interval_seconds").Default(5)
		t.Int("poll_count").Default(0)
		t.DateTime("last_polled_at", 6).Nullable()
		t.DateTime("approved_at", 6).Nullable()
		t.DateTime("denied_at", 6).Nullable()
		t.DateTime("consumed_at", 6).Nullable()
		t.DateTime("expires_at", 6)
		t.DateTime("created_at", 6).Default(migration.CurrentTimestamp)
		t.Index("client_id")
		t.Index("expires_at")
	}).Build()); err != nil {
		return err
	}

	return nil
}

func mig_20260101000000_create_oauth2_tables_down(tx *sql.Tx) error {
	if _, err := tx.Exec("DROP TABLE IF EXISTS oauth_device_codes"); err != nil {
		return err
	}
	if _, err := tx.Exec("DROP TABLE IF EXISTS oauth_refresh_tokens"); err != nil {
		return err
	}
	if _, err := tx.Exec("DROP TABLE IF EXISTS oauth_access_tokens"); err != nil {
		return err
	}
	if _, err := tx.Exec("DROP TABLE IF EXISTS oauth_auth_codes"); err != nil {
		return err
	}
	if _, err := tx.Exec("DROP TABLE IF EXISTS oauth_clients"); err != nil {
		return err
	}
	return nil
}
`
