package oauth2

// ConfigStub is the configuration file published into a project.
//
// It follows the shape queue and cache use: a config.Set of a single section,
// every leaf read through config.MustEnv so a deployment can override it
// without editing Go.
const ConfigStub = `package configs

import (
	"github.com/lemmego/api/config"
)

func init() {
	config.Set("oauth", config.M{
		// Where the endpoints are mounted. The discovery document and the
		// JWKS always live at the root, as RFC 8414 requires, and are not
		// affected by this.
		"route_prefix": config.MustEnv("OAUTH_ROUTE_PREFIX", "/oauth"),

		// The iss claim of every token, and the issuer in the discovery
		// document. Getting this wrong breaks every consumer and is
		// invisible until integration, so it is checked at boot.
		"issuer": config.MustEnv("OAUTH_ISSUER", config.MustEnv("APP_URL", "")),

		// The RSA keypair tokens are signed with. Generated by
		// ` + "`lemmego run oauth:keys`" + ` and kept out of version control:
		// storage/ is already gitignored.
		"keys": config.M{
			"path":   config.MustEnv("OAUTH_KEYS_PATH", "./storage/oauth"),
			"length": config.MustEnv("OAUTH_KEY_LENGTH", 2048),
		},

		"ttl": config.M{
			"access_token":   config.MustEnv("OAUTH_ACCESS_TOKEN_TTL", "1h"),
			"refresh_token":  config.MustEnv("OAUTH_REFRESH_TOKEN_TTL", "336h"),
			"auth_code":      config.MustEnv("OAUTH_AUTH_CODE_TTL", "60s"),
			"device_code":    config.MustEnv("OAUTH_DEVICE_CODE_TTL", "600s"),
			"personal_token": config.MustEnv("OAUTH_PERSONAL_TOKEN_TTL", "8760h"),
		},

		// PKCE is required of every client by default, not only public ones.
		// RFC 9700 recommends it for all of them.
		"require_pkce": config.MustEnv("OAUTH_REQUIRE_PKCE", true),

		// A refresh token is single use. Presenting a rotated one revokes
		// everything descended from the same grant, including the token the
		// honest client holds: one of the two holders is an attacker and the
		// server cannot tell which.
		"refresh_rotation": config.MustEnv("OAUTH_REFRESH_ROTATION", true),

		// How long a rotated refresh token still works, for clients that
		// crash between receiving one and storing it. Any non-zero value
		// measurably weakens reuse detection.
		"reuse_grace_period": config.MustEnv("OAUTH_REUSE_GRACE_PERIOD", "0s"),

		// Whether each request checks the token's revocation row.
		//   always — correct, one indexed read per request
		//   cached — reopens a revocation window as long as the cache TTL
		//   never  — a revoked token works until it expires
		"revocation": config.MustEnv("OAUTH_REVOCATION", "always"),

		// A first-party client is one the application itself owns, so there
		// is nobody to ask for consent.
		"skip_consent_for_first_party": config.MustEnv("OAUTH_SKIP_FIRST_PARTY_CONSENT", true),

		// Where to send someone who reaches the consent screen without being
		// signed in.
		"login_route": config.MustEnv("OAUTH_LOGIN_ROUTE", "/login"),

		// The scopes clients may request, and what to show on the consent
		// screen for each. A scope that is not listed here is rejected
		// rather than silently dropped.
		"scopes": config.M{},

		// Origins allowed to call the token and device endpoints from a
		// browser. Comma separated; empty means none.
		"cors_origins": config.MustEnv("OAUTH_CORS_ORIGINS", ""),

		// How long a revoked or expired row is kept before oauth:purge
		// removes it.
		"prune_after_hours": config.MustEnv("OAUTH_PRUNE_AFTER_HOURS", 168),

		"table_prefix": config.MustEnv("OAUTH_TABLE_PREFIX", "oauth_"),
	})
}
`

// MigrationVersion is the version the published migration registers under.
//
// It is a fixed constant rather than a timestamp taken when the file is
// written, which is how Passport does it too. A generated timestamp would
// differ on every run, so publishing twice would leave two migrations
// creating the same tables — and the migrator appends a duplicate version to
// its ordered list rather than rejecting it, which would run one of them
// twice. A constant makes a second publish a no-op, which is what anyone
// running it expects.
const MigrationVersion = "20260101000000"

// MigrationStub is the migration published into a project.
//
// Publishing it rather than creating the tables at boot is deliberate: the
// schema is something an application owns. It can be read, edited, and rolled
// back with every other migration, and it appears in schema_migrations where
// an operator expects to find it.
//
// It calls SchemaStatements rather than embedding the DDL, so the published
// file cannot drift from the schema this package actually reads and writes,
// and so it renders for whichever database the project migrates.
const MigrationStub = `package migrations

import (
	"database/sql"

	"github.com/lemmego/migration"
	"github.com/lemmego/oauth2"
)

func init() {
	migration.GetMigrator().AddMigration(&migration.Migration{
		Version: "` + MigrationVersion + `",
		Up:      mig_` + MigrationVersion + `_create_oauth2_tables_up,
		Down:    mig_` + MigrationVersion + `_create_oauth2_tables_down,
	})
}

func mig_` + MigrationVersion + `_create_oauth2_tables_up(tx *sql.Tx) error {
	// The dialect comes from the migrator, so this one file serves sqlite,
	// mysql and postgres. Statements are executed one at a time because an
	// index is its own statement outside MySQL, and the MySQL driver refuses
	// several at once unless the DSN opts in.
	for _, statement := range oauth2.SchemaStatements(migration.GetMigrator().Dialect(), "") {
		if _, err := tx.Exec(statement); err != nil {
			return err
		}
	}
	return nil
}

func mig_` + MigrationVersion + `_create_oauth2_tables_down(tx *sql.Tx) error {
	for _, table := range oauth2.TableNames("") {
		if _, err := tx.Exec("DROP TABLE IF EXISTS " + table); err != nil {
			return err
		}
	}
	return nil
}
`
